# Generated by Django 3.2.9 on 2021-11-28 18:32

from django.db import migrations
import stdimage.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='imagem',
            field=stdimage.models.StdImageField(upload_to='get_file_path', verbose_name='Imagem'),
        ),
    ]
